# https://stackoverflow.com/questions/25230376/how-to-automatically-install-ansible-galaxy-roles

# Install a role from the Ansible Galaxy
- src: gantsign.oh-my-zsh
- src: grzegorznowak.nvm_node

# Install a role from GitHub
# - name: opendaylight
#   src: https://github.com/dfarrell07/ansible-opendaylight

# Install a role from a specific git branch
# - name: opendaylight
#   src: https://github.com/dfarrell07/ansible-opendaylight
#   version: origin/master

# Install a role at a specific tag from GitHub
# - name: opendaylight
#   src: https://github.com/dfarrell07/ansible-opendaylight
#   version: 1.0.0

# Install a role at a specific commit from GitHub
# - name: opendaylight
#   src: https://github.com/dfarrell07/ansible-opendaylight
#   version: <commit hash>